# Generated by Django 4.1.7 on 2023-03-20 02:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import csvgenerator.constants
import csvgenerator.models.schema_dataset


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "column_separator",
                    models.CharField(
                        choices=[
                            (",", "Comma"),
                            ("|", "Pipe"),
                            (";", "Semicolon"),
                            ("\t", "Tab"),
                        ],
                        default=csvgenerator.constants.ColumnSeparator["COMMA"],
                        max_length=1,
                    ),
                ),
                (
                    "string_character",
                    models.CharField(
                        choices=[
                            ("'", "Single Quote"),
                            ('"', "Double Quote"),
                            ("`", "Backtick"),
                        ],
                        default=csvgenerator.constants.StringCharacter["DOUBLE_QUOTE"],
                        max_length=1,
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchemaDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("processing", "Processing"), ("ready", "Ready")],
                        max_length=32,
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=csvgenerator.models.schema_dataset.schema_directory_path,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csvgenerator.schema",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SchemaColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("full_name", "Full Name"),
                            ("job", "Job"),
                            ("email", "Email"),
                            ("domain_name", "Domain Name"),
                            ("phone_number", "Phone Number"),
                            ("company_name", "Company Name"),
                            ("text", "Text"),
                            ("integer", "Integer"),
                            ("address", "Address"),
                            ("date", "Date"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("min_value", models.CharField(blank=True, max_length=10)),
                ("max_value", models.CharField(blank=True, max_length=10)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csvgenerator.schema",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AddConstraint(
            model_name="schemacolumn",
            constraint=models.UniqueConstraint(
                fields=("schema", "name"), name="unique_column_name_per_schema"
            ),
        ),
        migrations.AddConstraint(
            model_name="schemacolumn",
            constraint=models.UniqueConstraint(
                fields=("schema", "order"), name="unique_column_order_per_schema"
            ),
        ),
        migrations.AddConstraint(
            model_name="schema",
            constraint=models.UniqueConstraint(
                fields=("name", "user_created"), name="unique_schema_name_owner"
            ),
        ),
    ]
